services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI} 
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env  

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"  # Uncomment this line if you want to access locally
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
