version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"  
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI} 
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env 
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
