services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network
    platform: linux/amd64
  mongodb:
    image: mongo:5.0
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data: