name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t muhammadfaiz19/pz-task5-docker .

      - name: Push Docker image to Docker Hub
        run: docker push muhammadfaiz19/pz-task5-docker

      - name: Deploy
        run: |
          docker pull muhammadfaiz19/pz-task5-docker
          docker stop pz-task5-docker || true
          docker rm pz-task5-docker || true
          docker run -d --env-file .env -p 4000:4000 --name pz-task5-docker muhammadfaiz19/pz-task5-docker

